authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

main/urls.py
from django.urls import path
from main.views import create_item_flutter, show_main, create_product, show_html, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import get_item_json, add_item_ajax, delete_item

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('html/', show_html, name= 'show_html'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('create-flutter/', create_item_flutter, name='create_product_flutter'),
]

tugas2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    description = models.TextField()
    amount = models.IntegerField(default=0)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as auth_logout

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)
    
@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)    

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from .models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.all()

    context = {
        'name': request.user.username, 
        'class': 'PBP D', 
        'items': items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_html(request):
    data = Item.objects.all()
    return render(request, 'show_html.html', {"items" : data})

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_item_json(request):
    item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
    
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user,)
        
        new_item.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def delete_item(request, id):
    if request.method == 'POST':
        item = Item.objects.get(id=id)
        if item.user == request.user:
            item.delete()
            return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<div class="container d-flex justify-center" style="justify-content: center; margin-top: 40px; background-color: rgb(0, 95, 38);border-radius: 40px; width: 1050px;">
    <h1 class="tulisan text-light text-center " style="justify-content: center; padding-top: 180px;" >Add New Item</h1>
    <div class="container d-flex justify-center" style="background-color: rgb(254, 199, 192); height: 450px;width:850px; border-radius: 40px;padding-top: 50px;">
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Add Item"/>
                    </td>
                </tr>
            </table>
        </form>
    
    </div>
</div>


{% endblock %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div class="container text-center" style="background-color:pink; min-height: 100vh; min-width: 100vw; display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <h1 class="display-4" style="font-weight: 500;">Tugas 3</h1>

        <div class="row">
            <div class="col" style="margin-top: 30px;text-align: left;margin-bottom: 20px;">
                <h5 class="mb-3">Name:</h5>
                <p class="mb-4">{{ name }}</p>

                <h5 class="mb-3">Class:</h5>
                <p class="mb-4">{{ class }}</p>

                <div class="d-flex justify-content-center">
                    <h5 class="mb-0">Sesi terakhir login: {{ last_login }}</h5>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <a href="{% url 'main:create_product' %}" class="btn btn-primary">
                Add New Item
            </a>

            <a href="{% url 'main:logout' %}" class="btn btn-danger ml-3">
                Logout
            </a>
        </div>
    </div>
{% endblock content %}

main/templates/show_html.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="background-color: pink; min-height: 100vh; min-width: 100vw;padding: 70px;">

    <div id="item_cards" class="row">
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item</button>
    
</div>


<script>
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }

    async function refreshItems() {
        document.getElementById("item_cards").innerHTML = ""
        const items = await getItems()
        let htmlString = ""
        htmlString+=`\n<p class="title" style="font-size: x-large; font-weight: bold;margin-bottom: 30px;">You have ${items.length} items</p>`
        
        items.forEach((item) => {
        htmlString += `\n <div class="col-md-4 mb-3">
        <div class="card {% if forloop.last %}bg-warning{% endif %}" style="border-radius: 10px;">
            <div class="card-body">
                <div class="r1 " style="display: flex; justify-content: space-between; align-items: center;margin-bottom:10px;">
                    <h1 class="card-title" style="font-size:30px;" >${item.fields.name}</h1>
                    <button class="btn btn-danger" onClick="deleteItem(${item.pk})">Delete</button>
                </div>
                <h6 class="card-subtitle mb-2 text-muted">${item.fields.amount}</h6>
                <p class="card-text">${item.fields.description}</p>
                <p class="card-text">${item.fields.date_added}</p>

        </div>
        </div>
        </div>`
        
        })
        
        document.getElementById("item_cards").innerHTML = htmlString
    }

    refreshItems()
    function addItem() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addItem

    function deleteItem(id) {
        fetch(`/delete_item/${id}/`, {
            method: "POST",
        }).then(refreshItems)
    }
</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Login</title>
{% endblock meta %}


{% block content %}

<div class="container d-flex justify-center" style="justify-content: center;">
    <div class = "login d-flex flex-column justify-content-center align-items-center " style="background-color: rgb(255, 213, 221); height: 500px; width: 1000px;text-align: center;margin-top:30px;border-radius: 40px;">
        <div class = "incontainer d-flex flex-column justify-content-center align-items-center" style="background-color: rgba(245, 245, 245, 0.628); height: 350px; width: 550px; border-radius: 40px">
            
            <div class = "text-center">
                
                <div>
                    
                    <h1 style="margin-bottom: 50px;">
                        Login</h1>
                
                <form method="POST" action="">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td>Username: </td>
                            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <td>Password: </td>
                            <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                        </tr>
                
                        <tr>
                            <td></td>
                            <td><input class="btn login_btn" type="submit" value="Login" style="background-color:rgb(234, 78, 185); margin-top: 30px; margin-bottom: 30px;"></td>
                        </tr>
                    </table>
                </form>
                
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}     
                    
                Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
            </div>
    </div>
</div>
</div>
    


</div>
</div>
</div>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  


<div class="container d-flex justify-center" style="justify-content: center;">
    <div class = "login d-flex flex-column justify-content-center align-items-center" style="background-color: rgb(255, 213, 221); height: 500px; width: 1000px;text-align: center;margin-top:30px;border-radius: 40px;">

            <h1>Register</h1>  
        
                <form method="POST" >  
                    {% csrf_token %}  
                    <table style="margin-top: 50px;">  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input type="submit" name="submit" value="Daftar" style="margin-top: 50px;"/></td>  
                        </tr>  
                    </table>  
                </form>
        
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        </div>
        
</div>

</div>  

{% endblock content %}